language: python
python:
    - "3.6.5"
install:
    - pip install -U pytest
    - pip install -U pytest-cov
    - pip install -U codecov
    - pip install -U pycodestyle
script:
    - pycodestyle ./src ./tests
    - PYTHONPATH=./ py.test --cov=./src tests
after_success:
    - codecov
