version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.5.6
        steps:
            - checkout
            - run: pwd
            - run: ls 
            - run: echo "Hello!"
