version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.5.6
        steps:
            - checkout
            - run: sudo pip install -U pytest
            - run: sudo pip install -U pytest-cov
            - run: sudo pip install -U codecov
            - run: sudo pip install -U pycodestyle
            - run: sudo pycodestyle ./src ./tests
            - run: PYTHONPATH=./ py.test --cov=./src tests
            - run: codecov
